version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    volumes:
      - ./flask:/flask'
    restart: always
    environment:
      - APP_NAME=FlaskServer
      - FLASK_DEBUG=1
    expose:
      - 8080
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - "5432"
    env_file:
      - .env